CREATE TABLE user_master (
    user_id      NUMBER(19)    PRIMARY KEY,
    x_user_id    NUMBER(19)    NOT NULL,
    firebase_uid VARCHAR2(128) UNIQUE,
    user_name    VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20)  NOT NULL,
    linked_at    TIMESTAMP,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE user_account_mapping (
    account_id   NUMBER(19)   NOT NULL,
    account_type VARCHAR2(10) NOT NULL,
    user_id      NUMBER(19)   NOT NULL,
    x_user_id    NUMBER(19)   NOT NULL,
    created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_user_account_mapping PRIMARY KEY (account_id, account_type)
);

CREATE TABLE transfer_user_mapping (
    transfer_id  NUMBER(19)   NOT NULL,
    x_user_id    NUMBER(19)   NOT NULL,
    created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_transfer_user_mapping PRIMARY KEY (transfer_id)
);

CREATE TABLE order_user_mapping (
    order_id     NUMBER(19)   NOT NULL,
    x_user_id    NUMBER(19)   NOT NULL,
    created_at   TIMESTAMP    DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_order_user_mapping PRIMARY KEY (order_id)
);

CREATE TABLE saga_transaction (
    saga_id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type VARCHAR2(50)  NOT NULL,
    transaction_key  VARCHAR2(255) NOT NULL UNIQUE,
    saga_status      VARCHAR2(30)  NOT NULL,
    current_step     VARCHAR2(100),
    total_steps      NUMBER(5),
    failure_reason   CLOB,
    rollback_yn      NUMBER(1)     DEFAULT 0 NOT NULL,
    started_at       TIMESTAMP     NOT NULL,
    completed_at     TIMESTAMP
);

CREATE TABLE saga_step_history (
    step_history_id  NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saga_id          NUMBER(19)    NOT NULL,
    step_name        VARCHAR2(100) NOT NULL,
    step_order       NUMBER(5)     NOT NULL,
    step_status      VARCHAR2(30)  NOT NULL,
    request_payload  CLOB,
    response_payload CLOB,
    error_message    CLOB,
    processed_at     TIMESTAMP     NOT NULL,
    CONSTRAINT fk_saga_step_saga FOREIGN KEY (saga_id) REFERENCES saga_transaction(saga_id)
);

CREATE TABLE idempotency_key (
    idempotency_key  VARCHAR2(255) PRIMARY KEY,
    request_hash     VARCHAR2(255) NOT NULL,
    request_type     VARCHAR2(100) NOT NULL,
    response_payload CLOB,
    status           VARCHAR2(30)  NOT NULL,
    expired_at       TIMESTAMP,
    created_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE outbox_event (
    outbox_id      NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR2(50)  NOT NULL,
    aggregate_id   NUMBER(19)    NOT NULL,
    event_type     VARCHAR2(100) NOT NULL,
    topic_name     VARCHAR2(255) NOT NULL,
    partition_key  VARCHAR2(255),
    payload        CLOB          NOT NULL,
    headers        CLOB,
    published_yn   NUMBER(1)     DEFAULT 0 NOT NULL,
    published_at   TIMESTAMP,
    retry_count    NUMBER(5)     DEFAULT 0 NOT NULL,
    created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_outbox_event_unpublished ON outbox_event (published_yn, created_at);

CREATE INDEX idx_saga_step_history_saga_id ON saga_step_history (saga_id);

CREATE TABLE dead_letter_event (
    dead_letter_id NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_topic VARCHAR2(255) NOT NULL,
    consumer_group VARCHAR2(255),
    payload        CLOB,
    error_message  CLOB,
    stack_trace    CLOB,
    retry_count    NUMBER(5)     DEFAULT 0 NOT NULL,
    resolved_yn    NUMBER(1)     DEFAULT 0 NOT NULL,
    resolved_at    TIMESTAMP,
    created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE reconciliation_result (
    reconciliation_id     NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_type   VARCHAR2(100) NOT NULL,
    source_system         VARCHAR2(100) NOT NULL,
    target_system         VARCHAR2(100) NOT NULL,
    source_count          NUMBER(19),
    target_count          NUMBER(19),
    mismatch_count        NUMBER(19),
    reconciliation_status VARCHAR2(30)  NOT NULL,
    checked_at            TIMESTAMP     NOT NULL
);

CREATE TABLE transaction_audit_log (
    transaction_audit_log_id NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type         VARCHAR2(100) NOT NULL,
    transaction_key          VARCHAR2(255) NOT NULL,
    transaction_status       VARCHAR2(50)  NOT NULL,
    source_system            VARCHAR2(100) NOT NULL,
    target_system            VARCHAR2(100),
    request_payload          CLOB,
    response_payload         CLOB,
    audited_at               TIMESTAMP     NOT NULL
);
