server:
  port: 8083

spring:
  application:
    name: transaction-server

  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: admin
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

core:
  bank:
    url: ${BANK_SERVER_URL:http://bank-server:8080}
  stock:
    url: ${STOCK_SERVER_URL:http://stock-server:8082}