package com.transaction.domain.saga.enums;

public enum SagaStepName {
    BANK_TRANSFER_REQUEST_CREATED,
    STOCK_CASH_DEPOSIT,
    BANK_TRANSFER_COMMIT,
    STOCK_CASH_WITHDRAW,
    STOCK_CASH_WITHDRAW_COMPENSATION,
    STOCK_CASH_DEPOSIT_COMPENSATION
}
